version: '3.7'

networks:
  ingress:
    external: true
  owncloud:
    external: false
volumes:

services:
  nginx:
    build: 
      context: ./config/nginx
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.network=ingress
      - traefik.port=80
      - traefik.backend=cloud
      - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ingress
      - owncloud
  owncloud:
    image: owncloud:10.0
    restart: unless-stopped
    volumes:
      - ./data/storage:/var/www/html
    networks:
      - owncloud